const resolve = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const pkg = require('./package.json');

module.exports = [
  {
    input: 'src/main.js',
    external: ['ms'],
    output: {
      file: pkg.main,
      format: 'cjs',
      // @urturn/runner uses the sourcemap to provide correct error traces
      sourcemap: true,
      // warn developers about editing the wrong files
      banner: `/**
[WARNING]: This file was auto generated by @urturn/runner package.
- Do NOT edit this file: all changes to room functions should go under your "src/" folder!
- See https://docs.urturn.app for more info
- Join discord if you have questions https://discord.gg/myWacjdb5S.
*/`,
    },
    // plugins that allow the src/main.js file require various npm packages
    // WARNING: packages that access the network, disk/file system will not work.
    plugins: [resolve(), commonjs()],
  },
];
