name: website-lint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Upgrade NPM
        run: npm install -g npm
      - name: lint-frontend
        run: |
          npm ci
          npm run lint
