name: Deploy UrTurn Documentation and Website Per PR
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: install and setup the monorepo dependencies
        run: |
          npm ci
          npx lerna bootstrap
      - name: build monorepo
        run: npx lerna run build
        env:
          REACT_APP_FIREBASE_CONFIG: ${{ secrets.REACT_APP_FIREBASE_CONFIG }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY }}
      - uses: actions/cache@v3
        id: cache-build
        with:
          path: .
          key: ${{ github.run_id }}-build
          restore-keys: ${{ github.run_id }}-build
  lint:
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/cache@v3
        id: cache-build
        with:
          path: .
          key: ${{ github.run_id }}-build
          restore-keys: ${{ github.run_id }}-build
      - name: all packages need to have lint script defined in package.json
        run: ./bin/every-package-json.sh ".scripts.lint != null"
      - name: all packages need to have lint:fix script defined in package.json
        run: ./bin/every-package-json.sh '.scripts."lint:fix" != null'
      - name: checking if packages are formatted properly (lint)
        run: npx lerna run lint
  preview_docs:
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/cache@v3
        id: cache-build
        with:
          path: .
          key: ${{ github.run_id }}-build
          restore-keys: ${{ github.run_id }}-build
      - name: Deploy UrTurn Docs Preview 🚀
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOCS }}'
          projectId: board-games-dev-e8c04
          entryPoint: docs
  preview_website:
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/cache@v3
        id: cache-build
        with:
          path: .
          key: ${{ github.run_id }}-build
          restore-keys: ${{ github.run_id }}-build
      - name: Deploy UrTurn Website Preview 🚀
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOARD_GAMES }}'
          projectId: board-games-io
          entryPoint: packages/website
