name: Publish example games

on:
  push:
    branches:
      - main

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    name: Build artifacts for frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install and setup the monorepo dependencies
        run: |
          npm ci
          npx lerna bootstrap
          npx lerna run build
      - name: Deploy examples/tictactoe 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: examples/tictactoe
          branch: published-tictactoe
